### ISSUE TITLE
post-install appears to rely on having pe-httpd on the master which will no longer be the case

### ISSUE THREAD

**Issue by npwalker** [adrienthebo/vagrant-pe_build#77]
With the advent of puppet server pe-httpd will no longer be running on the master.  

https://github.com/adrienthebo/vagrant-pe_build/blob/f57b41e703650fc01d29fcf01d5fd5563645f47b/lib/pe_build/provisioner/pe_bootstrap/post_install.rb

**Comment by Sharpie** [comment]
@npwalker Pushed a quick fix for this for a 0.10.2 bugfix release. More comprehensive handling of non-master infrastructure nodes will come when PR #82 gets merged.

For now, I'd recommend assigning the `:agent` role to anything that isn't a master --- that should prevent `pe_bootstrap` from running the master-specific post-install routine.
