### ISSUE TITLE
PE doesn't answer on 8140 after provisioning with Vagrant, vagrant-pe_build and vagrant-hosts

### ISSUE THREAD

**Issue by cvquesty** [adrienthebo/vagrant-pe_build#80]
I have a Vagrantfile I've been using without issue pre-3.7.x that provisions a master and 3 clients.  Once 3.7.0 came out, my Vagrantfile stopped working.  I've re-worked my Vagrantfile after reviewing the docs for vagrant-pe_build and vagrant-hosts, but still cannot make it work properly.  The issue *seems* to be that after provisioning, PE stops listening on 8140.  I login to the master, install telnet, and try and telnet to port 8140, and it does indeed reject the connection.

By doing a "vagrant ssh master" and running "puppet agent -t" as root, the following output occurs:

[root@master ~]# puppet agent -t
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: Connection refused - connect(2)
Info: Retrieving pluginfacts
Error: /File[/var/opt/lib/pe-puppet/facts.d]: Failed to generate additional resources using 'eval_generate': Connection refused - connect(2)
Error: /File[/var/opt/lib/pe-puppet/facts.d]: Could not evaluate: Could not retrieve file metadata for puppet://master.puppetlabs.vm/pluginfacts: Connection refused - connect(2)
Wrapped exception:
Connection refused - connect(2)
Info: Retrieving plugin
Error: /File[/var/opt/lib/pe-puppet/lib]: Failed to generate additional resources using 'eval_generate': Connection refused - connect(2)
Error: /File[/var/opt/lib/pe-puppet/lib]: Could not evaluate: Could not retrieve file metadata for puppet://master.puppetlabs.vm/plugins: Connection refused - connect(2)
Wrapped exception:
Connection refused - connect(2)
Info: Loading facts
Error: Could not retrieve catalog from remote server: Connection refused - connect(2)
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
Error: Could not send report: Connection refused - connect(2)

I'm not sure what to do, and the provisioning just isn't working properly.

**Comment by cvquesty** [comment]
Issue found (with a nod to James Sweeney).  The OOM killer was killing off the JVM in 3.7 where that wasn't an issue before.  Bumping the memory to 2048 for the master has solved the problem on all my test instances.

**Comment by moutons** [comment]
Link a Vagrantfile by uploading it as a Gist or as a file in a repo and using a hyperlink. I don't think there's a good way to embed the content, although you could preindent or surround the Vagrantfile with blockquotes e.g. 

```ruby
-- mode: ruby --

vi: set ft=ruby :

Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

# Define the Puppet Enterprise Version
config.pe_build.version = '3.7.1'
```

**Comment by cvquesty** [comment]
Hey there, bud!

I solved the issue, actually.  It revolved around memory on the master.

Check out:

https://github.com/cvquesty/vagrant-ss

**Comment by moutons** [comment]
haha I was actually digging to figure out why I can't sign into the console after bootstrapping 3.7.1 using oscar, just wanted to let you know about the markdown situation. they're looking into a safe way to enable embedding gists, but code fencing works (syntax highlight Vagrantfile as Ruby) fine. Thought it was neat to see you here since I went looking at yr blog to see if you'd posted anything related :smiley:
